### ISSUE TITLE
WiFi Status always be disabled after System boot

### ISSUE THREAD

**Issue by VargurErikson** [ManuelMcLure/OctoPrint-WiFiStatus#14]
Hi, 

I have the Problem, that Wifi-Status always will be disabled after a system reboot/boot ... then i activate the plugin, have to restart octoprint, but after system shutdown/boot/reboot it is disabled again.

Did i something wrong?

**Comment by ManuelMcLure** [comment]
**ATTENTION**
If the WiFi icon does not appear in the navigation bar and/or the plugin appears as disabled in the Plugin Manager, one of the following is the most likely cause:

- The plugin was installed on an operating system other than Linux.
- The OctoPrint installation is not running under Python 3.7 or higher.

This plugin is _only_ supported on Linux (including the Raspberry Pi) and if OctoPrint is running under Python 3.7 or higher. Note that it is not sufficient that Python 3.7 be installed on the system - OctoPrint must have been configured/upgraded to use Python 3.7 instead of Python 2.7. If you have installed OctoPi 0.17 or lower and have not taken explicit steps to upgrade to Python 3 then OctoPrint will still be running under Python 2.7 and this plugin _will not_ work. Upgrading OctoPrint from the version included in OctoPi to the latest version _will not_ make it run under Python 3 automatically.

To determine whether OctoPrint is running under Python 3.7 or higher, look at the very bottom of your OctoPrint UI in the browser, where there will be a line indicating the version of OctoPrint and the version of Python. If the Python version is not 3.7 or higher this plugin _will not_ work.

If you wish to upgrade your OctoPrint to use Python 3, please check out https://github.com/cp2004/Octoprint-Upgrade-To-Py3 for a script that will help you do the upgrade. Please note that if you use any plugins that have not yet been upgraded to support Python 3 they will be disabled after the upgrade, so weigh your options carefully.

There are _no_ plans to make the plugin work with Python 2.7, so please don't ask.

If your problem is one of the issues listed above these are _NOT_ bugs. _DO NOT_ open a bug issue if one of these is your problem. If your problem is something different, please delete this line and all text above, and _COMPLETELY_ fill out the template below.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

** Server**
Describe the server environment - what distribution and version of Linux on what hardware?
Is this an OctoPi installation or something different?
What version of Python is OctoPrint running under?

**Desktop (please complete the following information):**

- OS: [e.g. iOS]
- Browser [e.g. chrome, safari]
- Version [e.g. 22]

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6]
- OS: [e.g. iOS8.1]
- Browser [e.g. stock browser, safari]
- Version [e.g. 22]

**Logs**
Please go to the "Logging" settings page and add logging for `octoprint.plugins.wifistatus` with level `DEBUG`. Then reproduce the problem and upload the `octoprint.log` file to the issue.

**Additional context**
Add any other context about the problem here.

**Comment by VargurErikson** [comment]
On my System is running: OctoPrint 1.5.3 ... Python 3.7.3 ... and OctoPi 0.18.0

![Wifi-Status](https://user-images.githubusercontent.com/35312287/111911105-5e656c80-8a64-11eb-9931-d5a3fd4ad947.png)

When i activate Wifi Status and and restart OctoPrint, the Wifi-Status is available, but when i restart the System will be disabled.

Here is my Log-File
[octoprint.log](https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/files/6177787/octoprint.log)

**Comment by ManuelMcLure** [comment]
Hmmm... looks like the following is the culprit:
```
2021-03-21 16:30:47,418 - octoprint.plugin.core - ERROR - There was an error loading plugin wifistatus
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1526, in load_plugin
    plugin.load()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus/__init__.py", line 187, in __plugin_load__
    __plugin_implementation__ = WiFiStatusPlugin()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus/__init__.py", line 42, in __init__
    self.update_interface_list()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus/__init__.py", line 37, in update_interface_list
    for interface in getWNICnames():
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus/python3wifi/iwlibs.py", line 86, in getWNICnames
    ifnames = getConfiguredWNICnames()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_wifistatus/python3wifi/iwlibs.py", line 111, in getConfiguredWNICnames
    ifname = struct.unpack(f'{ifreq_bytes}s', ifname)[0]
struct.error: unpack requires a buffer of 32 bytes
```
Could be another instance of the issue discovered when adding multiple WiFi interfaces - a race condition where the interface is not yet active at OctoPrint startup.

**Comment by ManuelMcLure** [comment]
@VargurErikson would you please test a candidate fix? I can't reproduce this here so I'm depending on you.
Please use the OctoPrint Plugin Manager "Get More...->From URL" option with the following URL:
[https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/archive/refs/heads/startupracefix.zip](https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/archive/refs/heads/startupracefix.zip)

**Comment by VargurErikson** [comment]
Now the Plugin is available after system reboot, but no Status is shown 
![Screenshot_20210322-100046_Chrome](https://user-images.githubusercontent.com/35312287/111965117-ab455380-8af5-11eb-9c05-e8a29b3ae347.jpg)

**Comment by ManuelMcLure** [comment]
Can I get an `octoprint.log` from the new version? Make sure to enable debug logging for the WiFiStatus plugin.

**Comment by VargurErikson** [comment]
Here is my newest logfile

[octoprint (1).log](https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/files/6184183/octoprint.1.log)

**Comment by ManuelMcLure** [comment]
OK - I think I know what that problem is. Could you try reinstalling from the same URL as above? I've added a fix for the problem shown in your log.

**Comment by VargurErikson** [comment]
Hi @ManuelMcLure ... now it works great !!! Thanks for your help ;-)

**Comment by cruzer619** [comment]
I'm having the issue after getting fix.. 1.5.4  plugin shows but no data... and here is the small part of my log..
2021-03-23 22:24:15,913 - octoprint.plugins.wifistatus - DEBUG - WiFiStatus: timer fired!
2021-03-23 22:24:15,914 - octoprint.plugins.wifistatus - DEBUG - WiFiStatus: timer exception: ("'list' object has no attribute 'len'",)
2021-03-23 22:24:25,914 - octoprint.plugins.wifistatus - DEBUG - WiFiStatus: timer fired!
2021-03-23 22:24:25,915 - octoprint.plugins.wifistatus - DEBUG - WiFiStatus: timer exception: ("'list' object has no attribute 'len'",)

**Comment by cruzer619** [comment]
if anyone is reading this... for me.. I had to go from AUTO to wlan0.  to get the plugin to display info again after getting the 1.5.4 fix update.
