### ISSUE TITLE
[FR] Support multiple active WiFi interfaces

### ISSUE THREAD

**Issue by bobmagnuson** [ManuelMcLure/OctoPrint-WiFiStatus#8]
Love this plugin!  I use a seperate wifi adapter along with the built-in PI wifi adapter and would like to have the ability to display multiple or choose which wifi adapter status to display.

**Comment by ManuelMcLure** [comment]
Are both WiFi adapters enabled and connected at the same time? If only one is connected at a time the plugin _should_ "do the right thing" and only show information for the connected adapter.

I'm somewhat reluctant to add support for multiple simultaneous WiFi connections because I don't have an environment where I can tests this properly, and I want to make sure I don't break the "it just works" behavior with the much more common case of a single WiFi adapter.

I'll give this a think, but it will take some time for me to figure out whether this is something I really want to do and to get it implemented.

**Comment by ManuelMcLure** [comment]
@bobmagnuson I have a release candidate that might cover your requirements, but I don't have the hardware to test with. Please use the plugin manager's "Get more...from URL" feature with the following URL:
```
https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/archive/multiwifi.zip
```
to install the release candidate version and let me know if it works for you. Thanks!

**Comment by ManuelMcLure** [comment]
Ping @bobmagnuson - have you had a chance to test the changes out?

**Comment by pauvos** [comment]
Hi @ManuelMcLure , thanks for the plugin and the new multiwifi feature.

It basically works, there is just a minor issue after a system reboot. The plugin still displays the stats of my second wlan interface in the tooltip but the entry is missing on the settings page:

```diff
- AUTO, wlan0, wlan1
+ AUTO, wlan0
```

It reappears after restarting of the octoprint service. Maybe it doesn't have a SSID yet when the plugin initializes and gets filtered out?

**Comment by ManuelMcLure** [comment]
Thanks for testing. The list in the dropdown should reflect the list of available WiFi interfaces whether they are associated or not. If this is a USB WiFi adapter perhaps the OS hasn't detected it yet at the point OctoPrint starts up? I'll see if I can re-fetch the list of available interfaces each time the settings page pops up, but it will probably take me a day or two.

**Comment by ManuelMcLure** [comment]
@pauvos could you update to the latest code in the `multiwifi` branch and see if this fixes the issue you saw? It should now fetch the list of interfaces each time the settings page is populated so it should better handle a condition where the interface isn't available right at OctoPrint startup.

**Comment by ManuelMcLure** [comment]
The feature is now live in the latest release (1.5.0).
